# Generated by Django 3.1 on 2020-09-09 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrderSideType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(help_text='The symbol of the type', max_length=15, unique=True)),
                ('name', models.CharField(help_text='The human readable text', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='OrderType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(help_text='The symbol of the order type', max_length=25, unique=True)),
                ('name', models.CharField(help_text='The human readable text', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TimeInForce',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(help_text='GTK, IOC, or FOK', max_length=6, unique=True)),
                ('name', models.CharField(help_text='The human readable text', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(help_text='The symbol to be fill. etc... BTCUSD', max_length=8)),
                ('side', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.ordersidetype')),
                ('time_in_force', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.timeinforce')),
                ('type', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='home.ordertype')),
            ],
        ),
    ]
