# Generated by Django 3.1 on 2020-08-26 08:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.IntegerField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(default=None, help_text='Enter your first name', max_length=100)),
                ('last_name', models.CharField(default=None, help_text='Enter your last name', max_length=100)),
                ('phone', models.CharField(default=None, help_text='Enter your phone number', max_length=15)),
                ('street_address', models.CharField(default=None, help_text='Enter your address', max_length=255)),
                ('city', models.CharField(default=None, help_text='Enter your city', max_length=255)),
                ('zip_code', models.CharField(default=None, help_text='Entry your zip code', max_length=255)),
                ('referrer_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to='home.customer')),
            ],
            options={
                'ordering': ['customer_id'],
            },
        ),
    ]
