# Generated by Django 3.1 on 2020-09-06 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='time_in_force',
            field=models.CharField(choices=[('GTC', 'Good till Cancel'), ('IOC', 'Immediate or cancel'), ('FOK', 'Fill or Kill')], default='GTK', max_length=3),
        ),
    ]
