# Generated by Django 3.1 on 2020-09-07 03:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_order_time_in_force'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderSideType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(help_text='The symbol of the type', max_length=15)),
                ('name', models.CharField(help_text='The human readable text', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='OrderType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(help_text='The symbol of the order type', max_length=25)),
                ('name', models.CharField(help_text='The human readable text', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TimeInForce',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(help_text='GTK, IOC, or FOK', max_length=6)),
                ('name', models.CharField(help_text='The human readable text', max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='order',
            name='side',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='home.ordersidetype'),
        ),
        migrations.AlterField(
            model_name='order',
            name='time_in_force',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='home.timeinforce'),
        ),
        migrations.AlterField(
            model_name='order',
            name='type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='home.ordertype'),
        ),
    ]
