# Generated by Django 3.1 on 2020-08-26 08:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20200826_0855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_uuid',
            field=models.UUIDField(auto_created=True, default=uuid.uuid4),
        ),
    ]
