# Generated by Django 3.1 on 2020-08-26 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20200826_0858'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='referrer_id',
            new_name='referrer',
        ),
    ]
